// working: 120, intruder: 100

export const SPLINTER_WORKING_QUOTES = [
  'Splinter gave me a choice. I chose the harder path.',
  'The mission is not finished until the build is clean.',
  'A bug avoided in planning is a victory in production.',
  'Patience. Even a cloud agent must breathe before the push.',
  'Do not fear the refactor. Fear the untested deploy.',
  'The repo is a garden. Pull weeds, do not trample the flowers.',
  'One does not rush a PR, one earns it.',
  'Listen to the logs. They whisper what the user cannot.',
  'A wise dev tests twice and merges once.',
  'Your form was unclear. Clarify the requirement, then strike.',
  'The channel watches. Make every commit worthy of QA.',
  'Ghost walks where the branch is silent. So should your diff.',
  'He who ships on Friday owns the Saturday incident.',
  'Small commits, young turtle. Large commits break the shell.',
  'The webhook hears all. Configure it with respect.',
  'In triage there is no shame, only the next card.',
  'Trust the Mini App, but verify the initData.',
  'The Trello list is a river. Cards must flow.',
  'When in doubt, read index.ts again.',
  'Discipline is choosing the test suite when no one is watching.',
  'A flaky test is a teacher in disguise. Listen before you delete.',
  'The Worker wakes on every request. Treat each one as sacred.',
  'Code review is not combat. It is sparring with respect.',
  'Splinter gave me a choice. I chose to read the stack trace.',
  'Deploy slowly, observe deeply, rollback without shame.',
  'The Mini App opens a door. initData is the lock.',
  'A card without steps to reproduce is fog on the river.',
  'I do not guess. I gather evidence first.',
  'The webhook failed silently once. We learned to log everything.',
  'Patience in triage saves hours in production.',
  'Your PR description is a letter to your future self. Write it well.',
  'Cloudflare Workers are fast. Your assumptions should be faster to question.',
  'The board remembers every card you moved without reading.',
  'A green CI badge is peace. Do not disturb it without reason.',
  'Splinter gave me a choice. I chose integration tests over hope.',
  'The Telegram channel is loud. The logs are honest.',
  'One broken webhook can flood a channel. Guard the endpoint.',
  'Review your diff as if a stranger wrote it. Be kind, be thorough.',
  'The sensei does not skip type checks.',
  'Bugs hide where confidence is highest. Doubt is a tool.',
  'A deploy is a bow. Aim before you release the arrow.',
  'Trello labels are colors of intent. Use them with purpose.',
  'The Mini App user trusts the UI. Honor that trust in every handler.',
  'Staging is where courage meets caution.',
  'Splinter gave me a choice. I chose to fix the root cause.',
  'He who mocks the linter will weep at midnight.',
  'I maintain the bot so the channel stays calm.',
  'Read the card twice. Move it once.',
  'A timeout is the universe asking you to retry with wisdom.',
  'Workers cold start. Minds should warm up with tests first.',
  'The PR that cannot be reviewed cannot be merged.',
  'Webhook signatures exist for a reason. Verify them.',
  'Discipline is closing the loop on every bug report.',
  'The river of cards flows toward Done. Obstructions are our training.',
  'Splinter gave me a choice. I chose small diffs.',
  'Do not ship secrets. The repo is forever.',
  'A wise maintainer reads the diff before the description.',
  'Your test is documentation that never lies.',
  'The bot speaks to many. I speak to one admin with focus.',
  'Cloudflare edge is near. Your bug may be nearer than you think.',
  'Patience with flaky CI beats rage-pushing to main.',
  'The Mini App initData expired. Teach the user to refresh, not blame them.',
  'Every /report is a student asking for help. Answer with clarity.',
  'The Trello API rate limit is a lesson in humility.',
  'Splinter gave me a choice. I chose to write the regression test.',
  'Merge conflicts are puzzles, not punishments.',
  'A silent Worker is either perfect or unobserved. Assume neither.',
  'Code review finds what pride hides.',
  'The webhook payload tells a story. Read every field.',
  'I triage code, not feelings. Be precise.',
  'Deploy with a plan. Roll back with a clearer one.',
  'The channel button is a promise. Keep the handler true.',
  'A bug in production was once a skipped test in development.',
  'Splinter gave me a choice. I chose observability over optimism.',
  'Patience. The agent is thinking. So should you.',
  'Your branch name should tell a story, not a joke.',
  'The list named Backlog is not a graveyard. Tend it.',
  'Workers KV remembers. Choose what you store with care.',
  'A PR without tests is a letter without a stamp.',
  'The sensei merges when green, never when tired.',
  'Webhook retries are second chances. Make the handler idempotent.',
  'Triage is sorting truth from noise. Sharpen your ears.',
  'The Mini App must work offline gracefully where it can.',
  'Splinter gave me a choice. I chose to document the webhook flow.',
  'Read the error message. All of it.',
  'A wise dev fears the one-line fix that touches five systems.',
  'I serve the dojo. The dojo serves the users.',
  'Cloudflare logs are scrolls. Study them after every deploy.',
  'The card moved to Done too fast was never truly done.',
  'Discipline is saying no to scope creep in a hotfix.',
  'Your coworker\'s PR deserves the review you wish for yours.',
  'The Telegram update may duplicate. Design for it.',
  'Splinter gave me a choice. I chose explicit over clever.',
  'A broken Mini App init check protects the whole dojo.',
  'Tests that fail intermittently demand respect, not ignorance.',
  'The maintainer\'s agent runs with keys. Guard them like swords.',
  'Push to preview before you push to production.',
  'The Trello comment is a breadcrumb for the next warrior.',
  'Webhook verification failed. That is success, not failure.',
  'Patience with new contributors builds a stronger repo.',
  'Splinter gave me a choice. I chose to read the issue before coding.',
  'A deploy without a changelog is a story half told.',
  'The Worker binding name must match wrangler. Check twice.',
  'Code review is where bugs go to be enlightened.',
  'I do not fear the long thread. I fear the vague ask.',
  'The bot handler should fail closed, not open.',
  'Every bug card is a teacher wearing a mask.',
  'Splinter gave me a choice. I chose the boring solution that works.',
  'He who disables ESLint for speed will parse errors by hand.',
  'The Mini App deep link must land somewhere sensible.',
  'A PR comment should instruct, not humiliate.',
  'The river stalls when cards lack owners. Assign with care.',
  'Workers secrets are not for the client. Ever.',
  'Splinter gave me a choice. I chose to wait for CI.',
  'Listen to the user report. Then listen to the logs.',
  'Trello attachments carry evidence. Ask for them.',
  'The webhook secret rotated. Update every environment.',
  'Discipline is fixing the test before fixing the code.',
  'Splinter gave me a choice. I chose clarity over speed.',
  'Splinter gave me a choice. I chose the path of the regression test and the calm deploy.',
] as const;

export { TURTLE_INTRUDER_TEASES as SPLINTER_INTRUDER_QUOTES } from './turtle-teases';
