// turtle teases: 100

export const TURTLE_INTRUDER_TEASES = [
  '{who}, hatchling on attempt {count}: you mistook /master-splinter for a pizza order line. Splinter does not deliver. Train with /report.',
  'Young turtle {who}, the locked dojo door giggled at knock #{count}. Master Splinter stays with the admin. File your shame through /bug.',
  '{who}, attempt {count} and you still think the sewer pipe leads to admin. It leads to /report. Master Splinter has spoken.',
  'Shell up, {who}. Break-in #{count} earns no pizza, no audience with the sensei, no mercy, only homework via /bug.',
  '{who}, the rat watched you rattle /master-splinter {count} times. He sipped tea. You will sip humility and use /report.',
  'Dojo rule #{count} for {who}: students file bugs; senseis summon agents. You are not a sensei. Not yet. Try /bug.',
  '{who}, Master Splinter heard your {count}th tap and yawned. The cloud is for the keeper. Your courtyard is /report.',
  'Legendary persistence, {who}, attempt {count}. Legendary clearance? Still zero. Splinter sends you to /bug with love.',
  '{who}, you stormed the inner screen like a sewer hero on try {count}. The door is locked. Your weapon is /report.',
  'Master Splinter to {who}, visit {count}: the shell protects the body, not unauthorized commands. /master-splinter is not yours.',
  '{who}, even Michelangelo would not spam the sensei {count} times. Channel that energy into /bug, little turtle.',
  'Attempt {count}, {who}. The inner shrine remains closed. Offer screenshots at the altar of /report instead.',
  '{who}, you scratch the Splinter terminal on knock {count}. The terminal scratches back with denial. Use /bug.',
  'Young one {who}, after {count} tries the dojo floor knows your footprints. The admin logs know you are not admin. /report.',
  '{who}, pizza arrives hot; permissions arrive earned. Attempt {count} bought you neither. File through /report or /bug.',
  'The sewer echoes {who}, {who}, {who}, attempt {count}. Echoes do not grant an audience with Master Splinter. Honest /bug reports might.',
  '{who}, Splinter respects the hustle on break-in #{count}. He disrespects the shortcut. Return to student forms: /report.',
  'Turtle {who}, you reached for Master Splinter like it was the last slice, try {count}. The slice is for the maintainer. You get /bug.',
  '{who}, attempt {count}: the locked door is not a personality test. You failed anyway. Study /report.',
  'Sensei note for {who} after {count} knocks: enthusiasm 10/10, clearance 0/10. Graduate via /bug, not /master-splinter.',
  '{who}, the dojo Wi‑Fi password is not /master-splinter. You have tried {count} times. The password is still /report.',
  'Break-in score {count}, {who}. Your rank is curious, not keeper. Master Splinter meditates until the admin wakes it. Use /bug.',
  '{who}, on attempt {count} you asked the cloud rat for keys. He offered you a /bug form instead. Accept the gift.',
  'Young turtle {who}, I build for one admin. You build character on attempt {count}. Build with /report.',
  '{who}, Splinter\'s private chamber smells of incense and denial, visit {count}. Knock elsewhere: /bug.',
  'Attempt {count}, {who}. You cannot sudo your way into Splinter\'s heart. You can document issues with /report.',
  '{who}, the turtles trained years before touching sacred tools. You touched /master-splinter on try {count}. Untouch /report.',
  'Dojo announcement: {who} has pinged the forbidden command {count} times. Reward: extra training. Path: /bug.',
  '{who}, sewer storming is admirable on attempt {count}. Storming the sensei is not your quest. Quest log says /report.',
  'Master Splinter squints at {who}, attempt {count}. Not the admin, he mutters. Perhaps a reporter. Go to /report.',
  '{who}, you treat /master-splinter like a gacha pull, try {count}. You pulled access denied again. Pity route: /bug.',
  'Knock {count}, {who}. The door says no in three languages. Splinter adds a fourth: use /report, young turtle.',
  '{who}, I am behind the screen on attempt {count}. You are on the tourist side. Tickets sold at /bug.',
  'Young turtle {who}, your shell is thick but attempt {count} proves the admin wall is thicker. File at /report.',
  '{who}, Splinter would tip his hat to your {count} tries if hats solved permissions. They do not. /bug does.',
  'Attempt {count}, {who}: the dojo cat swats /master-splinter out of your hands. It is a rat. Catch /report.',
  '{who}, you cannot ninja-flip into my chamber\'s DMs on try {count}. Ninjas file recon via /report first.',
  'Break-in #{count}, {who}. Master Splinter labels you spirited hatchling. Master Splinter labels you unauthorized. Label your bug with /bug.',
  '{who}, the inner sanctum heard you {count} times and chose peace. Choose /report and let the sensei sleep.',
  'Turtle {who}, attempt {count} at the forbidden gate is good cardio. Bad ops. Sweat into a /report instead.',
  '{who}, you wanted Splinter\'s agent; you got Splinter\'s lecture. Visit {count}. Homework: /bug with steps to reproduce.',
  'On try {count}, {who}, the cloud dojo replied nice turtle, wrong belt. White belt activities include /report.',
  '{who}, even the foot clan would not brute-force /master-splinter {count} times. Take the high road: /bug.',
  'Attempt {count}, {who}. Pizza party is in the sewer. The admin chamber is behind me. You were not invited. /report is open.',
  '{who}, Splinter keeps a scroll of attempt counts. You are on line {count}. Next column says send them to /report.',
  'Young turtle {who}, I maintain the bot so you can complain properly, via /bug, not attempt {count} on /master-splinter.',
  '{who}, the locked door appreciates your {count} rhythmic knocks. It will not open. The help desk will: /report.',
  'Sensei roast #{count} for {who}: you chase Master Splinter like it is a rooftop skateboard. Dismount. File /bug.',
  '{who}, attempt {count} proves you read the command list. Splinter wishes you read the permissions list. Start /report.',
  'Dojo fax to {who}, re: break-in {count}: Master Splinter is unavailable. Fax back: detailed /bug.',
  '{who}, you are the {count}th turtle to confuse master with my account. Spoiler: not your account. Use /report.',
  'Master Splinter to {who}: Again? Attempt {count}. Again, he says, use /bug.',
  '{who}, the sewer is free; I am not for hire by hatchlings by the admin. Your {count} coins bounce off the turnstile. Try /report.',
  'Young one {who}, shell check on try {count}: hard shell, soft clearance. Harden your reports via /bug.',
  '{who}, Splinter\'s tea cooled while you spammed /master-splinter {count} times. Warm it with a quality /report.',
  'Attempt {count}, {who}. The dojo moon is beautiful tonight. The admin endpoint is not for you. /report is.',
  '{who}, you knock like a hero on #{count}. The script kiddie path is closed. The reporter path smells like /bug.',
  'Turtle {who}, Master Splinter heard fix it {count} times from you. It waits for the keeper. You wait for /report.',
  '{who}, break-in {count}: Splinter adds you to the wall of almost learned discipline. Almost. Finish with /report.',
  'Young turtle {who}, the /master-splinter button is not a shell eject button, try {count} proved that. Eject your bug via /bug.',
  '{who}, attempt {count} and the rats in the wall applaud your persistence. They do not applaud your access. /report.',
  'Sensei says, {who}, visit {count}: discipline is knowing which command is yours. Yours is /report, not Master Splinter.',
  '{who}, you treat attempt {count} like a speedrun. Speedrun /bug with repro steps instead.',
  'Knock knock, {who}. Who\'s there on try {count}? Not the admin. Master Splinter agrees. Splinter sends /report.',
  '{who}, the dojo vending machine ate your {count} tokens for /master-splinter. It dispenses /bug forms only.',
  'Attempt {count}, {who}. Leonardo would plan. You pinged. Raphael would file /report. Be Raphael today.',
  '{who}, Splinter\'s whiskers twitch at break-in #{count}. Twitch means no. No means /bug.',
  'Young turtle {who}, I am not a group chat on attempt {count}. It is a locked workshop. You are in the lobby: /report.',
  '{who}, you have {count} notches on your shell from denied tries. Carve a notch for a filed /report instead.',
  'Master Splinter whispers to {who} on attempt {count}: The agent serves the keeper. You serve the users, through /bug.',
  '{who}, sewer legend status unlocked at try {count}. Admin legend status: locked. Key alternative: /report.',
  'Attempt {count}, {who}. The pizza box said admin. It lied. So did /master-splinter. Truth lives in /report.',
  '{who}, you Master Splinter heard your knock\'s doorbell {count} times. The admin slept through it. Splinter did not. He points at /bug.',
  'Young one {who}, the cloud sensei does not take apprentices via Telegram spam on #{count}. Apprentices file /report.',
  '{who}, Splinter grades attempt {count}: A for effort, F for authorization. Extra credit: /bug with logs.',
  'Turtle {who}, on knock {count} the locked door played a sad flute. Play a happy tune: submit /report.',
  '{who}, I build pipelines, not friendships, try {count}. Befriend /report; it always answers.',
  'Break-in {count}, {who}. You are not banned; you are redirected. Splinter redirects with love to /bug.',
  '{who}, the dojo firewall recognized your shell on attempt {count}. Recognition is not admission. /report is admission to the conversation.',
  'Young turtle {who}, Splinter keeps the cloud on a leash. You keep pulling on try {count}. Leash wins. Walk to /report.',
  '{who}, attempt {count}: you cannot out-stubborn a rat who has seen centuries of impatience. Out-report him instead via /bug.',
  'Sensei log, {who}, event {count}: unauthorized /master-splinter. Prescription: sunlight, water, /report.',
  '{who}, the inner dojo screen flickered at your {count}th poke. Flicker is not access. Clarity is /bug.',
  'Attempt {count}, {who}. Master Splinter would share pizza with you. He will not share me. File bugs at /report.',
  '{who}, you stormed the cloud on try {count} with heart. Storm the issue tracker with /report and screenshots.',
  'Young turtle {who}, my sign says staff only in every font on attempt {count}. Read it. Obey /bug.',
  '{who}, Splinter counted your knocks: {count}. He counted your permissions: one fewer than needed. Use /report.',
  'Turtle {who}, the /master-splinter command is not a secret combo on attempt {count}. The combo is /bug, steps, expected, actual.',
  '{who}, break-in #{count} made the sewer rats gossip. Gossip does not elevate your role. /report might elevate the fix.',
  'Master Splinter to {who}, visit {count}: You fight the door. Fight the bug instead. Door wins unless you /report.',
  '{who}, attempt {count} and Master Splinter still thinks you are a very polite denial letter. Rewrite yourself via /bug.',
  'Young one {who}, the dojo elevator does not go to admin on try {count}. Take the stairs to /report.',
  '{who}, Splinter\'s robe has no pockets for spare API keys, knock {count}. Your pockets should hold repro steps for /report.',
  'Attempt {count}, {who}. You cannot trade {count} tries for an audience with Master Splinter. Trade them for one excellent /bug.',
  '{who}, the locked door engraved your name on try {count}. Engraving says student. Students use /bug.',
  'Turtle {who}, I am sharpening tools for the keeper while you sharpen excuses on attempt {count}. Sharpen a report instead.',
  '{who}, sewer pizza night is Thursday. Admin night is not your night, #{count} proved it. Bug night is any night: /report.',
  'Young turtle {who}, Splinter applauds attempt {count} then points at the exit sign labeled /report.',
  '{who}, on try {count} you asked the universe for Master Splinter. The universe sent Splinter. Splinter sent /bug.',
  'Break-in score {count}, {who}. The dojo leaderboard lists top reporters, not top spammers. Climb with /report.',
] as const;
